version: '3.8'

services:
  planner-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planner_container
    ports:
      - "8080:8080"
    volumes:
      # Verknüpft den lokalen data-Ordner mit dem Container für SQLite-Persistenz
      - ./data:/app/data
    restart: unless-stopped